#SurveyJS release pipeline (load builds)

#trigger only "by hand"
trigger: none
pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- checkout: self
  persistCredentials: true
  clean: true

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: '9434af9c-19e5-4e5d-8bd7-2d9129d3fed4'
    pipeline: '34'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyJSVersionFile'
    downloadPath: '$(System.ArtifactsDirectory)'
  displayName: 'Download Build Artifact - SurveyJSVersionFile'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSVersionFile/'
    Contents: 'version.txt'
    TargetFolder: '$(Build.Repository.LocalPath)/'
    OverWrite: true
  displayName: 'Copy Build Artifact - SurveyJSVersionFile'

- powershell: |
    $version = Get-Content $(Build.Repository.LocalPath)/version.txt
    Write-Host "##vso[task.setvariable variable=SurveyJSVersion;]$version"
  displayName: 'setup SurveyJSVersion variable from SurveyJSVersionFile'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'install Node.js'

#load builds
- powershell: |
    npm init -f
    npm install survey-analytics@$(SurveyJSVersion)
    npm install survey-core@$(SurveyJSVersion)
    npm install survey-angular@$(SurveyJSVersion)
    npm install survey-jquery@$(SurveyJSVersion)
    npm install survey-knockout@$(SurveyJSVersion)
    npm install survey-react@$(SurveyJSVersion)
    npm install survey-vue@$(SurveyJSVersion)
    npm install survey-pdf@$(SurveyJSVersion)
    npm install survey-creator@$(SurveyJSVersion)
    npm install surveyjs-editor
    npm install surveyjs-widgets@$(SurveyJSVersion)
  displayName: 'install the correspondent version of SurveyJS packages from NPM'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'node_modules/survey-analytics/'
    Contents: |
      survey.analytics.js
      survey.analytics.min.js
      survey.analytics.css
      survey.analytics.min.css
    TargetFolder: '$(SurveyJSVersion)'
    CleanTargetFolder: true
    OverWrite: true
  displayName: 'copy build files - survey-analytics'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'node_modules/survey-core/'
    Contents: |
      survey.core.js
      survey.core.min.js
      modern.css
      modern.min.css
      survey.css
      survey.min.css
    TargetFolder: '$(SurveyJSVersion)'
    OverWrite: true
  displayName: 'copy build files - survey-core'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'node_modules/survey-angular/'
    Contents: |
      survey.angular.js
      survey.angular.min.js
    TargetFolder: '$(SurveyJSVersion)'
    OverWrite: true
  displayName: 'copy build files - survey-angular'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'node_modules/survey-jquery/'
    Contents: |
      survey.jquery.js
      survey.jquery.min.js
    TargetFolder: '$(SurveyJSVersion)'
    OverWrite: true
  displayName: 'copy build files - survey-jquery'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'node_modules/survey-knockout/'
    Contents: |
      survey.ko.js
      survey.ko.min.js
    TargetFolder: '$(SurveyJSVersion)'
    OverWrite: true
  displayName: 'copy build files - survey-knockout'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'node_modules/survey-react/'
    Contents: |
      survey.react.js
      survey.react.min.js
    TargetFolder: '$(SurveyJSVersion)'
    OverWrite: true
  displayName: 'copy build files - survey-react'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'node_modules/survey-vue/'
    Contents: |
      survey.vue.js
      survey.vue.min.js
      survey-vue.js
    TargetFolder: '$(SurveyJSVersion)'
    OverWrite: true
  displayName: 'copy build files - survey-vue'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'node_modules/survey-pdf/'
    Contents: |
      survey.pdf.js
      survey.pdf.min.js
    TargetFolder: '$(SurveyJSVersion)'
    OverWrite: true
  displayName: 'copy build files - survey-pdf'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'node_modules/survey-pdf/'
    Contents: |
      survey.pdf.js
      survey.pdf.min.js
    TargetFolder: '$(SurveyJSVersion)'
    OverWrite: true
  displayName: 'copy build files - survey-pdf'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'node_modules/survey-creator/'
    Contents: |
      survey-creator.js
      survey-creator.min.js
      survey-creator.css
      survey-creator.min.css
    TargetFolder: '$(SurveyJSVersion)'
    OverWrite: true
  displayName: 'copy build files - survey-creator'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'node_modules/surveyjs-editor/'
    Contents: |
      surveyeditor.js
      surveyeditor.min.js
      surveyeditor.css
      surveyeditor.min.css
    TargetFolder: '$(SurveyJSVersion)'
    OverWrite: true
  displayName: 'copy build files - surveyjs-editor'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'node_modules/surveyjs-widgets/'
    Contents: |
      surveyjs-widgets.js
      surveyjs-widgets.min.js
      surveyjs-widgets.min.js.map
      widgets/**
    TargetFolder: '$(SurveyJSVersion)'
    OverWrite: true
  displayName: 'copy build files - surveyjs-widgets'

- powershell: |
    echo $(git --version)
    git config --global user.email "kurmanov.work@gmail.com"
    git config --global user.name "dmitrykurmanov"
    git checkout master
    git pull origin master
    git fetch --tags --force
    git add $(SurveyJSVersion)/*
    git commit -m "released $(SurveyJSVersion)"
    git push origin master
  displayName: 'push build files to the surveyjs/builds repo'


#trigger next build via the artifact file 'version.txt'
- task: CopyFiles@2
  inputs:
    contents: 'version.txt'
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'copy version file to Build.ArtifactStagingDirectory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SurveyJSVersionFile'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifact - SurveyJSVersionFile'
